return {
PlaceObj('ModItemBuildingTemplate', {
	'Group', "Production",
	'Id', "Indoor_PolymerPlant",
	'template_class', "PolymerPlant",
	'resource_produced1', "Polymers",
	'max_storage1', 40000,
	'production_per_day1', 18000,
	'pin_rollover_hint', T(106007276846, --[[ModItemBuildingTemplate Indoor_PolymerPlant pin_rollover_hint]] "<image UI/Infopanel/left_click.tga 1400> Select"),
	'pin_rollover_hint_xbox', T(136881049838, --[[ModItemBuildingTemplate Indoor_PolymerPlant pin_rollover_hint_xbox]] "<image UI/PS4/Cross.tga> View"),
	'construction_cost_Concrete', 20000,
	'construction_cost_Metals', 10000,
	'construction_cost_MachineParts', 10000,
	'build_points', 14000,
	'require_prefab', true,
	'is_tall', true,
	'dome_required', true,
	'upgrade1_id', "PolymerPlant_FactoryAI",
	'upgrade1_display_name', T(379785261608, --[[ModItemBuildingTemplate Indoor_PolymerPlant upgrade1_display_name]] "Factory AI"),
	'upgrade1_description', T(606846753711, --[[ModItemBuildingTemplate Indoor_PolymerPlant upgrade1_description]] "+<upgrade1_mul_value_1>% Production."),
	'upgrade1_icon', "UI/Icons/Upgrades/factory_ai_01.tga",
	'upgrade1_upgrade_cost_Electronics', 10000,
	'upgrade1_upgrade_cost_MachineParts', 4000,
	'upgrade1_mod_label_1', "PolymerPlant",
	'upgrade1_mod_prop_id_1', "production_per_day1",
	'upgrade1_mul_value_1', 20,
	'upgrade2_id', "PolymerPlant_Automation",
	'upgrade2_display_name', T(109992553217, --[[ModItemBuildingTemplate Indoor_PolymerPlant upgrade2_display_name]] "Automation"),
	'upgrade2_description', T(916583707199, --[[ModItemBuildingTemplate Indoor_PolymerPlant upgrade2_description]] "Decreases Workplaces by <abs(upgrade2_add_value_1)>."),
	'upgrade2_icon', "UI/Icons/Upgrades/automation_01.tga",
	'upgrade2_upgrade_cost_Polymers', 10000,
	'upgrade2_upgrade_cost_Electronics', 10000,
	'upgrade2_mod_label_1', "PolymerPlant",
	'upgrade2_mod_prop_id_1', "max_workers",
	'upgrade2_add_value_1', -4,
	'upgrade3_id', "PolymerPlant_Amplify",
	'upgrade3_display_name', T(337859732126, --[[ModItemBuildingTemplate Indoor_PolymerPlant upgrade3_display_name]] "Amplify"),
	'upgrade3_description', T(169807623886, --[[ModItemBuildingTemplate Indoor_PolymerPlant upgrade3_description]] "+<upgrade3_mul_value_1>% Production; + Consumption."),
	'upgrade3_icon', "UI/Icons/Upgrades/amplify_01.tga",
	'upgrade3_upgrade_cost_Polymers', 10000,
	'upgrade3_mod_label_1', "PolymerPlant",
	'upgrade3_mod_prop_id_1', "production_per_day1",
	'upgrade3_mul_value_1', 25,
	'upgrade3_mod_label_2', "PolymerPlant",
	'upgrade3_mod_prop_id_2', "electricity_consumption",
	'upgrade3_add_value_2', 40000,
	'maintenance_resource_type', "MachineParts",
	'maintenance_resource_amount', 4000,
	'consumption_resource_type', "Fuel",
	'consumption_max_storage', 10000,
	'display_name', T(558637609228, --[[ModItemBuildingTemplate Indoor_PolymerPlant display_name]] "Polymer Factory"),
	'display_name_pl', T(532190304009, --[[ModItemBuildingTemplate Indoor_PolymerPlant display_name_pl]] "Polymer Factories"),
	'description', T(670478914975, --[[ModItemBuildingTemplate Indoor_PolymerPlant description]] "Produces Polymers from Water and Fuel."),
	'build_category', "Production",
	'display_icon', "UI/Icons/Buildings/polymer_plant.tga",
	'build_pos', 9,
	'entity', "MachinePartsFactory",
	'encyclopedia_id', "PolymerPlant",
	'encyclopedia_image', "UI/Encyclopedia/PolymerFactory.tga",
	'label1', "InsideBuildings",
	'label2', "FactoryBuildings",
	'palette_color1', "life_accent_1",
	'palette_color2', "outside_base",
	'palette_color3', "outside_accent_factory",
	'demolish_sinking', range(15, 25),
	'electricity_consumption', 20000,
	'enabled_shift_2', false,
	'enabled_shift_3', false,
	'max_workers', 12,
	'specialist', "engineer",
	'water_consumption', 2000,
}),
PlaceObj('ModItemCode', {
	'FileName', "Code/Script.lua",
}),
}
